ballerina-platform/module-ballerinax-java.jms

.gitignore, Ballerina.lock, Ballerina.toml, pom.xml, src/jms/Module.md, src/jms/connection.bal, src/jms/destination.bal, src/jms/error.bal, src/jms/external_functions.bal, src/jms/main.bal, src/jms/session.bal, src/jms/tests/connection_test.bal, src/jms/tests/main_test.bal, utils/pom.xml, utils/src/main/java/org/wso2/ei/module/jms/BallerinaJmsException.java, utils/src/main/java/org/wso2/ei/module/jms/JmsConnectionUtils.java, utils/src/main/java/org/wso2/ei/module/jms/JmsConstants.java, utils/src/main/java/org/wso2/ei/module/jms/JmsSessionUtils.java, utils/src/main/java/org/wso2/ei/module/jms/JmsUtils.java, utils/src/main/java/org/wso2/ei/module/jms/LoggingExceptionListener.java, utils/src/main/java/org/wso2/ei/module/jms/Utils.java
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Migrate JMS code base to Ballerina 1.0.0 alpha

pom.xml, src/jms/error.bal, utils/src/main/java/org/wso2/ei/module/jms/JmsMessageListenerUtils.java
> 1. Upgrade the Ballerina version to alpha 3
2. A custom error should be public, otherwise its getting conflict with ballerina error.
=> upgarde ballerina version

Ballerina.lock, pom.xml
JMS module compile in the ballerina 1.0.0
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Compile module in ballerina 1.0.0

Ballerina.toml
Ballerina.toml file update necessary details. 
> Link(s) to product documentation that addresses the changes of this PR. If no …
=> Update Ballerina.toml file with license, authors, keywords, repository

src/jms/destination.bal, utils/src/main/java/org/wso2/ei/module/jms/JmsDestinationUtils.java
The issue reported in the https://github.com/ballerina-platform/ballerina-lang/issues/19100 should
be fixed. I have to change the current implementation to handle the null value.
> Brief description of the new …
=> Fix NullPointerException changing the implementation

.gitignore, README.md, jms/Ballerina.lock, jms/Ballerina.toml, jms/src/jms/Module.md, jms/src/jms/abstract_message.bal, jms/src/jms/bytes_message.bal, jms/src/jms/map_message.bal, jms/src/jms/message.bal, jms/src/jms/stream_message.bal, jms/src/jms/text_message.bal, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMessageUtils.java
setJMSCorrelationID and setJMSCorrelationIDAsBytes methods added to the JMS connector.
> Link(s) to product documentation that …
=> Add setJMSCorrelationID and setJMSCorrelationIDAsBytes methods

pom.xml
=> Add SLF4J Simple version

jms/src/jms/Module.md
A summary added to Module.md file that required for Ballerina Central.
> Link(s) to product documentation that addresses the …
=> Add module summary

compiler-plugin/pom.xml, compiler-plugin/src/main/java/org/wso2/ei/b7a/jms/ServiceCompilerPlugin.java, jms/Ballerina.toml, jms/pom.xml, pom.xml, utils/pom.xml
Version bump from 0.6.0 to 0.6.1
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Bump version to 0.6.1

utils/src/main/java/org/wso2/ei/b7a/jms/Constants.java
`VERSION` constant update to 0.6.1
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Update the VERSION constant to 0.6.1

utils/src/main/java/org/wso2/ei/b7a/jms/Constants.java, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMessageListenerUtils.java
JMS listener not working issue fixed by changing the `setMessageListener` and input for the `BPackage` constructor.
> Link(s) …
=> Fix JMS listener not working issue

.travis.yml, README.md, jms/Ballerina.lock, jms/src/jms/Module.md
> - Update README.md and Module.md
> - Bump ballerina version.
> - Configure travis build.
=> Fix JMS module build

.travis.yml, compiler-plugin/pom.xml, jms/Ballerina.toml, jms/pom.xml, pom.xml, utils/pom.xml
> Revert updating version to snapshot version.
=> Revert updating version to snapshot version

jms/src/jms/message_consumer.bal, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMessageListenerUtils.java
The existing implementation of `setMessageListener` is written to read `any` type object. It had to cast to `ObjectValue`. Now the ballerina language support `service` type into the inter-op function. The JMS implementation changed accordingly.
> Summary of user …
=> Change setMessageListener to read a service object

compiler-plugin/pom.xml, compiler-plugin/src/main/java/org/wso2/ei/b7a/jms/ServiceCompilerPlugin.java, jms/Ballerina.lock, jms/Ballerina.toml, jms/pom.xml, pom.xml, utils/pom.xml, utils/src/main/java/org/wso2/ei/b7a/jms/Constants.java
Version update from 0.6.1 to 0.6.2
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Bump JMS version to 0.6.2

jms/src/jms/bytes_message.bal, jms/src/jms/map_message.bal, jms/src/jms/message.bal, jms/src/jms/message_consumer.bal, utils/src/main/java/org/wso2/ei/b7a/jms/JmsBytesMessageUtils.java, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMapMessageUtils.java, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMessageUtils.java
Ballerina lang having an issue returning array|error union in the inter-op call. The fix is temporarily to return the RuntimeException and handle it with the `trap`. We should revert this after language fix available.
> Summary of user stories addressed by this …
=> Fix array|error union returning issue in interop temporarily

jms/Ballerina.lock, jms/src/jms/map_message.bal, jms/src/jms/message.bal, pom.xml, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMapMessageUtils.java, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMessageUtils.java
To support for ballerina version 1.0.5
=> to support for ballerina version 1.0.5

.travis.yml, compiler-plugin/src/main/java/org/wso2/ei/b7a/jms/ServiceCompilerPlugin.java, jms/Ballerina.lock, jms/Ballerina.toml, pom.xml, utils/src/main/java/org/wso2/ei/b7a/jms/JmsBytesMessageUtils.java, utils/src/main/java/org/wso2/ei/b7a/jms/JmsConnectionUtils.java, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMapMessageUtils.java, utils/src/main/java/org/wso2/ei/b7a/jms/JmsMessageUtils.java
> Upgrade ballerina version to 1.1.0 
> Resolve the compilation errors occurred due to version change
> Upgrade ballerina version to 1.1.0
=> Fix the compilation errors due to ballerina version upgrade 1.1.0

.travis.yml, java.jms/Ballerina.toml, pom.xml
=> Update travis.yml 

README.md, compiler-plugin/pom.xml, compiler-plugin/src/main/java/org.ballerinalang.java.jms/ServiceCompilerPlugin.java, compiler-plugin/src/main/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin, java.jms/Ballerina.lock, java.jms/Ballerina.toml, java.jms/pom.xml, java.jms/src/java.jms/Module.md, java.jms/src/java.jms/bytes_message.bal, java.jms/src/java.jms/connection.bal, java.jms/src/java.jms/destination.bal, java.jms/src/java.jms/map_message.bal, java.jms/src/java.jms/message.bal, java.jms/src/java.jms/message_consumer.bal, java.jms/src/java.jms/session.bal, pom.xml, utils/pom.xml, utils/src/main/java/org/ballerinalang/java/jms/BallerinaJmsException.java, utils/src/main/java/org/ballerinalang/java/jms/Constants.java, utils/src/main/java/org/ballerinalang/java/jms/JmsBytesMessageUtils.java, utils/src/main/java/org/ballerinalang/java/jms/JmsConnectionUtils.java, utils/src/main/java/org/ballerinalang/java/jms/JmsDestinationUtils.java, utils/src/main/java/org/ballerinalang/java/jms/JmsMapMessageUtils.java, utils/src/main/java/org/ballerinalang/java/jms/JmsMessageListenerUtils.java, utils/src/main/java/org/ballerinalang/java/jms/JmsMessageUtils.java, utils/src/main/java/org/ballerinalang/java/jms/JmsProducerUtils.java, utils/src/main/java/org/ballerinalang/java/jms/JmsSessionUtils.java, utils/src/main/java/org/ballerinalang/java/jms/JmsUtils.java, utils/src/main/java/org/ballerinalang/java/jms/LoggingExceptionListener.java, utils/src/main/java/org/wso2/ei/b7a/jms/Constants.java
> $title
> Code sample
```ballerina
import ballerina/log;
import ballerina/java.jms;
jms:Connection connection = check jms:createConnection({
initialContextFactory: "org.apache.activemq.jndi.ActiveMQInitialContextFactory",
providerUrl: "tcp://localhost:61616"
});
jms:Session session = check connection->createSession({acknowledgementMode: "AUTO_ACKNOWLEDGE"});
jms:Destination queue = check session->createQueue("MyQueue");
listener jms:MessageConsumer jmsConsumer = check session->createConsumer(queue);
service messageListener on jmsConsumer {
resource function onMessage(jms:Message message) {
if (message is jms:TextMessage) {
var val = message.getText();
if (val is string) {
log:printInfo("Message received: " + val );
} else {
log:printInfo("Message received without text");
}
} else { …
```
=> Fix issue in receiving messages asynchronously [Message Listener]

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, compiler-plugin/pom.xml, examples/jms-durable-topic-message-subscriber/jms_durable_topic_message_subscriber.bal, examples/jms-queue-message-receiver-with-client-acknowledgment/jms_queue_message_receiver_with_client_acknowledgment.bal, examples/jms-topic-message-subscriber/jms_topic_message_subscriber.bal, examples/send-jms-message-to-http-endpoint/send_jms_message_to_http_endpoint.bal, java.jms/Ballerina.lock, java.jms/Ballerina.toml, java.jms/pom.xml, java.jms/src/java.jms/Module.md, pom.xml, utils/pom.xml, utils/src/main/java/org/ballerinalang/java/jms/Constants.java
> $title
https://github.com/ballerina-platform/module-ballerina-java.jms/pull/60
Fixes https://github.com/ballerina-platform/module-ballerina-java.jms/issues/59
=> Update docs for Ballerina Swan Lake Preview 1

.github/workflows/ci.yml, .github/workflows/release.yml
$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Update ballerina action in github actions

.github/workflows/ci.yml, .github/workflows/release.yml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Update maven build command

java.jms/pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Update ballerina command

.github/workflows/ci.yml, .github/workflows/release.yml
Reverts ballerina-platform/module-ballerina-java.jms#68
=> Revert "Update maven build command"

changelog.md, gradle.properties
> $subject
Part of: [#4669](https://github.com/ballerina-platform/ballerina-standard-library/issues/4669)
N/A
=> Update module version

README.md, ballerina/Module.md, ballerina/Package.md
=> Update library documentation

README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/Module.md, ballerina/Package.md, ballerina/connection.bal
=> Remove `jms:createConnection` API

README.md, ballerina/Module.md, ballerina/Package.md
=> Update package documentation with activemq.driver references

native/src/main/java/io/ballerina/stdlib/java.jms/ConsumerUtils.java
=> Fix message-property extracting logic

.github/workflows/pull-request.yml
=> Stop running tests on windows-build

README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/Module.md, ballerina/Package.md, ballerina/connection.bal, ballerina/message_listener.bal, ballerina/session.bal, native/src/main/java/io/ballerina/stdlib/java.jms/ConsumerUtils.java
> $subject
* Remove `jms:SessionConfiguration` record and introduced `jms:AcknowledgementMode` enum.
N/A
=> Update session configurations

pom.xml
> $subject
Fixes: [#4693](https://github.com/ballerina-platform/ballerina-standard-library/issues/4693)
N/A
=> Update ballerina runtime version

java.jms/Ballerina.lock
> $subject
Part of: [#4693](https://github.com/ballerina-platform/ballerina-standard-library/issues/4693)
N/A
=> Update ballerina-lock file

compiler-plugin/pom.xml, java.jms/Ballerina.lock, java.jms/Ballerina.toml, java.jms/pom.xml, pom.xml, utils/pom.xml, utils/src/main/java/org/ballerinalang/java/jms/Constants.java
> $subject
Part of: [#4693](https://github.com/ballerina-platform/ballerina-standard-library/issues/4693)
N/A
=> Update package version

ballerina/session.bal, native/src/main/java/io/ballerina/stdlib/java.jms/JmsSession.java
=> Add `commit` and `rollback` functionality to JMS session

ballerina/connection.bal, ballerina/session.bal
=> Update return type for `createSession` API

ballerina/session.bal, native/src/main/java/io/ballerina/stdlib/java.jms/JmsSession.java
=> Add `close` API to JMS session

ballerina/message_producer.bal, native/src/main/java/io/ballerina/stdlib/java.jms/JmsProducer.java
=> Add `close` API to JMS MessageProducer

README.md, ballerina/Module.md, ballerina/Package.md
=> Update package documentation

ballerina/message_consumer.bal
=> Add runtime validation for MessageConsumer options

ballerina/message_consumer.bal
=> Update message consumer-options validation

ballerina/message.bal, ballerina/message_producer.bal, native/src/main/java/io/ballerina/stdlib/java.jms/CommonUtils.java, native/src/main/java/io/ballerina/stdlib/java.jms/JmsConnection.java, native/src/main/java/io/ballerina/stdlib/java.jms/JmsConsumer.java, native/src/main/java/io/ballerina/stdlib/java.jms/JmsMessageListenerUtils.java, native/src/main/java/io/ballerina/stdlib/java.jms/JmsMessageUtils.java, native/src/main/java/io/ballerina/stdlib/java.jms/JmsProducer.java, native/src/main/java/io/ballerina/stdlib/java.jms/JmsSession.java
=> Refactor `java.jms` codebase

ballerina/message.bal, ballerina/message_producer.bal, native/src/main/java/io/ballerina/stdlib/java.jms/JmsMessageUtils.java
=> Add functionality to set replyTo and correlationId to the message

.github/workflows/build-with-bal-test-graalvm.yml
=> Update graalvm workflow

.github/workflows/build-with-bal-test-graalvm.yml, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/build.gradle, ballerina/tests/test_commons.bal, build-config/resources/Ballerina.toml, build.gradle, gradle.properties
=> Use `ballerinax/activemq.driver` instead of ActiveMQ client jar

pom.xml
=> Bump `mime4j` version to `0.8.9`

ballerina/tests/jms_connection_tests.bal
=> Fix failing test case

.github/workflows/build-with-bal-test-graalvm.yml
=> Update graalvm workflow to support JDK17 migration

ballerina/caller.bal, ballerina/connection.bal, ballerina/message_consumer.bal, ballerina/message_listener.bal, ballerina/message_producer.bal, ballerina/session.bal
=> Update API docs

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update dependency versions

ballerina/connection.bal
=> Remove unwanted default values

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/tests/resources/docker-compose.yaml, gradle.properties
=> Update ActiveMQ driver version

ballerina/tests/resources/docker-compose.yaml
=> Update ActiveMQ image version

docs/spec/spec.md
=> Fix the wording in the JMS specification

ballerina/build.gradle
=> Update package build configurations

.github/workflows/pull-request.yml
=> Fix PR build not working

ballerina/Dependencies.toml, ballerina/message.bal, ballerina/message_producer.bal, ballerina/tests/failover_connection_tests.bal, ballerina/tests/jms_consumer_tests.bal, ballerina/tests/jms_listener_tests.bal, ballerina/tests/jms_producer_tests.bal, ballerina/tests/jms_queue_tests.bal, ballerina/tests/jms_session_client_ack_tests.bal, ballerina/tests/jms_session_dups_ok_ack_tests.bal, ballerina/tests/jms_session_transacted_tests.bal, ballerina/tests/jms_svc_consumer_types_tests.bal, ballerina/tests/jms_topic_tests.bal, changelog.md, docs/spec/spec.md, native/src/main/java/io/ballerina/stdlib/java.jms/CommonUtils.java, native/src/main/java/io/ballerina/stdlib/java.jms/Constants.java, native/src/main/java/io/ballerina/stdlib/java.jms/MessageConverter.java, native/src/main/java/io/ballerina/stdlib/java.jms/consumer/Actions.java, native/src/main/java/io/ballerina/stdlib/java.jms/listener/MessageDispatcher.java, native/src/main/java/io/ballerina/stdlib/java.jms/producer/Actions.java
> $subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/8079
=> Revamp `jms:Message` API
